import pytest
from fastapi.testclient import TestClient
from unittest.mock import patch, AsyncMock, MagicMock
from app.main import app
from app.services.deepseek_service import DeepSeekService

client = TestClient(app)

# Mock data
MOCK_USER_ID = "test_user_123"
MOCK_TOKEN = "valid_token"
MOCK_REPLY = "This is a mock reply generated by DeepSeek."
MOCK_POST = "This is a mock LinkedIn post generated by DeepSeek. #ai #content"
MOCK_REWRITE = "This is a rewritten version of the LinkedIn post. #professional #engaging"

@pytest.fixture
def mock_verify_token():
    with patch("app.middleware.auth.verify_token", new_callable=AsyncMock) as mock:
        mock.return_value = MOCK_USER_ID
        yield mock

@pytest.fixture
def mock_credit_service():
    with patch("app.routes.content_routes.credit_service") as mock:
        mock.has_sufficient_credits = AsyncMock(return_value=True)
        mock.deduct_credits = AsyncMock(return_value=9)  # 9 credits remaining after deduction
        yield mock

@pytest.fixture
def mock_deepseek_service():
    with patch.object(DeepSeekService, "generate_reply", new_callable=AsyncMock) as mock:
        mock.return_value = MOCK_REPLY
        yield mock

# Reply Generation Tests
def test_generate_reply_unauthorized():
    """Test reply generation without authentication"""
    response = client.post("/content/reply", json={
        "post_content": "Test post content",
        "tone": "professional"
    })
    assert response.status_code == 401
    assert "detail" in response.json()

@pytest.mark.asyncio
async def test_generate_reply_insufficient_credits(
    mock_verify_token,
    mock_deepseek_service
):
    """Test reply generation with insufficient credits"""
    with patch("app.routes.content_routes.credit_service") as mock_credits:
        mock_credits.has_sufficient_credits = AsyncMock(return_value=False)
        mock_credits.deduct_credits = AsyncMock()  # Should not be called
        
        response = client.post(
            "/content/reply",
            json={
                "post_content": "Test post content",
                "tone": "professional"
            },
            headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
        )
        
        assert response.status_code == 402
        assert "Insufficient credits" in response.json()["detail"]
        mock_credits.deduct_credits.assert_not_called()

@pytest.mark.asyncio
async def test_generate_reply_success(
    mock_verify_token,
    mock_credit_service,
    mock_deepseek_service
):
    """Test successful reply generation"""
    response = client.post(
        "/content/reply",
        json={
            "post_content": "Test post content",
            "tone": "professional"
        },
        headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["reply"] == MOCK_REPLY
    assert data["credits_remaining"] == 9
    
    # Verify credit service calls
    mock_credit_service.has_sufficient_credits.assert_called_once_with(MOCK_USER_ID, 1)
    mock_credit_service.deduct_credits.assert_called_once_with(MOCK_USER_ID, 1)
    
    # Verify DeepSeek service call
    mock_deepseek_service.assert_called_once_with(
        post_content="Test post content",
        tone="professional"
    )

@pytest.mark.asyncio
async def test_generate_reply_api_error(
    mock_verify_token,
    mock_credit_service
):
    """Test handling of DeepSeek API errors"""
    with patch.object(
        DeepSeekService,
        "generate_reply",
        new_callable=AsyncMock,
        side_effect=Exception("API Error")
    ):
        response = client.post(
            "/content/reply",
            json={
                "post_content": "Test post content",
                "tone": "professional"
            },
            headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
        )
        
        assert response.status_code == 500
        assert "Failed to generate reply" in response.json()["detail"]
        
        # Verify credits were not deducted
        mock_credit_service.deduct_credits.assert_not_called()

# Post Generation Tests
@pytest.fixture
def mock_post_generation():
    with patch.object(DeepSeekService, "generate_post", new_callable=AsyncMock) as mock:
        mock.return_value = MOCK_POST
        yield mock

def test_generate_post_unauthorized():
    """Test post generation without authentication"""
    response = client.post("/content/post", json={
        "topic": "AI in Healthcare",
        "tone": "professional"
    })
    assert response.status_code == 401
    assert "detail" in response.json()

@pytest.mark.asyncio
async def test_generate_post_insufficient_credits(
    mock_verify_token,
    mock_post_generation
):
    """Test post generation with insufficient credits"""
    with patch("app.routes.content_routes.credit_service") as mock_credits:
        mock_credits.has_sufficient_credits = AsyncMock(return_value=False)
        mock_credits.deduct_credits = AsyncMock()  # Should not be called
        
        response = client.post(
            "/content/post",
            json={
                "topic": "AI in Healthcare",
                "tone": "professional",
                "target_audience": "healthcare professionals",
                "key_points": ["Improved diagnosis", "Efficient workflows"]
            },
            headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
        )
        
        assert response.status_code == 402
        assert "Insufficient credits" in response.json()["detail"]
        mock_credits.deduct_credits.assert_not_called()

@pytest.mark.asyncio
async def test_generate_post_success(
    mock_verify_token,
    mock_credit_service,
    mock_post_generation
):
    """Test successful post generation"""
    response = client.post(
        "/content/post",
        json={
            "topic": "AI in Healthcare",
            "tone": "professional",
            "target_audience": "healthcare professionals",
            "key_points": ["Improved diagnosis", "Efficient workflows"],
            "max_length": 1500
        },
        headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["post_content"] == MOCK_POST
    assert data["credits_remaining"] == 9
    
    # Verify credit service calls
    mock_credit_service.has_sufficient_credits.assert_called_once_with(MOCK_USER_ID, 1)
    mock_credit_service.deduct_credits.assert_called_once_with(MOCK_USER_ID, 1)
    
    # Verify DeepSeek service call
    mock_post_generation.assert_called_once_with(
        topic="AI in Healthcare",
        tone="professional",
        target_audience="healthcare professionals",
        key_points=["Improved diagnosis", "Efficient workflows"],
        max_length=1500
    )

@pytest.mark.asyncio
async def test_generate_post_api_error(
    mock_verify_token,
    mock_credit_service
):
    """Test handling of DeepSeek API errors in post generation"""
    with patch.object(
        DeepSeekService,
        "generate_post",
        new_callable=AsyncMock,
        side_effect=Exception("API Error")
    ):
        response = client.post(
            "/content/post",
            json={
                "topic": "AI in Healthcare",
                "tone": "professional"
            },
            headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
        )
        
        assert response.status_code == 500
        assert "Failed to generate post" in response.json()["detail"]
        
        # Verify credits were not deducted
        mock_credit_service.deduct_credits.assert_not_called()

# Post Rewriting Tests
@pytest.fixture
def mock_post_rewriting():
    with patch.object(DeepSeekService, "rewrite_post", new_callable=AsyncMock) as mock:
        mock.return_value = MOCK_REWRITE
        yield mock

def test_rewrite_post_unauthorized():
    """Test post rewriting without authentication"""
    response = client.post("/content/rewrite", json={
        "post_content": "Original post content",
        "tone": "professional"
    })
    assert response.status_code == 401
    assert "detail" in response.json()

@pytest.mark.asyncio
async def test_rewrite_post_insufficient_credits(
    mock_verify_token,
    mock_post_rewriting
):
    """Test post rewriting with insufficient credits"""
    with patch("app.routes.content_routes.credit_service") as mock_credits:
        mock_credits.has_sufficient_credits = AsyncMock(return_value=False)
        mock_credits.deduct_credits = AsyncMock()  # Should not be called
        
        response = client.post(
            "/content/rewrite",
            json={
                "post_content": "Original post content",
                "tone": "professional",
                "preserve_key_points": True,
                "additional_instructions": "Make it more engaging"
            },
            headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
        )
        
        assert response.status_code == 402
        assert "Insufficient credits" in response.json()["detail"]
        mock_credits.deduct_credits.assert_not_called()

@pytest.mark.asyncio
async def test_rewrite_post_success(
    mock_verify_token,
    mock_credit_service,
    mock_post_rewriting
):
    """Test successful post rewriting"""
    response = client.post(
        "/content/rewrite",
        json={
            "post_content": "Original post content",
            "tone": "professional",
            "preserve_key_points": True,
            "max_length": 1500,
            "additional_instructions": "Make it more engaging"
        },
        headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["rewritten_content"] == MOCK_REWRITE
    assert data["credits_remaining"] == 9
    
    # Verify credit service calls
    mock_credit_service.has_sufficient_credits.assert_called_once_with(MOCK_USER_ID, 1)
    mock_credit_service.deduct_credits.assert_called_once_with(MOCK_USER_ID, 1)
    
    # Verify DeepSeek service call
    mock_post_rewriting.assert_called_once_with(
        post_content="Original post content",
        tone="professional",
        preserve_key_points=True,
        max_length=1500,
        additional_instructions="Make it more engaging"
    )

@pytest.mark.asyncio
async def test_rewrite_post_api_error(
    mock_verify_token,
    mock_credit_service
):
    """Test handling of DeepSeek API errors in post rewriting"""
    with patch.object(
        DeepSeekService,
        "rewrite_post",
        new_callable=AsyncMock,
        side_effect=Exception("API Error")
    ):
        response = client.post(
            "/content/rewrite",
            json={
                "post_content": "Original post content",
                "tone": "professional"
            },
            headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
        )
        
        assert response.status_code == 500
        assert "Failed to rewrite post" in response.json()["detail"]
        
        # Verify credits were not deducted
        mock_credit_service.deduct_credits.assert_not_called()

@pytest.mark.asyncio
async def test_rewrite_post_with_minimal_params(
    mock_verify_token,
    mock_credit_service,
    mock_post_rewriting
):
    """Test post rewriting with minimal required parameters"""
    response = client.post(
        "/content/rewrite",
        json={
            "post_content": "Original post content",
            "tone": "professional"
        },
        headers={"Authorization": f"Bearer {MOCK_TOKEN}"}
    )
    
    assert response.status_code == 200
    data = response.json()
    assert data["rewritten_content"] == MOCK_REWRITE
    assert data["credits_remaining"] == 9
    
    # Verify DeepSeek service call with default values
    mock_post_rewriting.assert_called_once_with(
        post_content="Original post content",
        tone="professional",
        preserve_key_points=True,
        max_length=None,
        additional_instructions=None
    ) 